---
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: ^3.5.4
flutter:
  assets:
    - Assets/
  uses-material-design: true
name: test1
publish_to: none
version: 1.0.0+1