---
dependencies:
  cupertino_icons: ^1.0.8
  firebase_storage: ^12.3.4
  flutter:
    sdk: flutter
  flutter_email_sender: ^6.0.3
  http: ^1.2.2
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: ^3.5.4
flutter:
  assets:
    - Assets/
  uses-material-design: true
name: test1
publish_to: none
version: 1.0.0+1